---
# tasks file for roles/prometheus_role
---
- name: update server
  yum:
    name:
    state: latest
  tags: 
    - step1
- name: Download prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.42.0/prometheus-2.42.0.linux-amd64.tar.gz
    dest: /usr/local/bin
    checksum: 422dab055ed9c7bcaff52b718705f9192c6fac0de6b7e78dd278e70ee2663dcc
  tags:
    - step2
- name: Extract tar file
  unarchive:
    src: /usr/local/bin/prometheus-2.42.0.linux-amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
  tags: 
    - step3

- name: creating a systemd file for prometheus service 
  copy:
    src: /home/ubuntu/prometheus.service
    dest: /etc/systemd/system/prometheus.service
    owner: ec2-user
    group: ec2-user
    mode: '0744'
  tags: 
    - step4
- name: reload service
  systemd:
    daemon_reload: yes
  tags: 
    - step5
- name: start prometheus
  service:
    name: prometheus
    state: started      
  tags:
    - step6


